# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: MAcro02-Grupo02

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    
    - uses: actions/checkout@v4
    
    - name: Install Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 15
      
    - name: Build and Test
      run: |
          xcodebuild build \
           -project MAcro02-Grupo02/MAcro02-Grupo02.xcodeproj \
           -scheme MAcro02-Grupo02 \
           -sdk iphonesimulator \
           -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' \
            test || exit 1
